language: python
sudo: required
dist: xenial

matrix:
  include:
    # Sanity
    - name: Stable Sanity
      python: 3.7
      install:
        - pip install ansible
      script:
        - ansible-test sanity --docker default -v
    - name: Devel Sanity
      python: 3.7
      install:
        - pip install git+https://github.com/ansible/ansible.git@devel#egg=ansible
      script:
        - ansible-test sanity --docker default -v

    # Units
    - name: Stable Units
      python: 3.7
      install:
        - pip install ansible
      script:
        - ansible-test units --docker default -v
    - name: Devel Units
      python: 3.7
      install:
        - pip install git+https://github.com/ansible/ansible.git@devel#egg=ansible
      script:
        - ansible-test units --docker default -v

    # CentOS 7 Integration
    - name: CentOS 7 Stable Integration
      python: 3.7
      install:
        - pip install ansible
      script:
        - ansible-test integration --docker centos7 -v go
    - name: CentOS 7 Devel Integration
      python: 3.7
      install:
        - pip install git+https://github.com/ansible/ansible.git@devel#egg=ansible
      script:
        - ansible-test integration --docker centos7 -v go

    # Ubuntu 18.04 Integration
    - name: Ubuntu 18.04 Stable Integration
      python: 3.7
      install:
        - pip install ansible
      script:
        - ansible-test integration --docker ubuntu1804 -v go
    - name: Ubuntu 18.04 Devel Integration
      python: 3.7
      install:
        - pip install git+https://github.com/ansible/ansible.git@devel#egg=ansible
      script:
        - ansible-test integration --docker ubuntu1804 -v go

before_script:
  - mkdir -p ~/.ansible/collections/ansible_collections/sivel
  - mv $(pwd) ~/.ansible/collections/ansible_collections/sivel
  - cd ~/.ansible/collections/ansible_collections/sivel/toiletwater
  - ansible-test env

notifications:
  email:
    - matt@sivel.net
