language: python
sudo: required
dist: xenial

matrix:
  include:
    # - python: 3.7
    #   install:
    #     - pip install ansible
    - python: 3.7
      install:
        - pip install git+https://github.com/ansible/ansible.git@devel#egg=ansible

install:
  - ls -al
  - mkdir -p ~/.ansible/collections/ansible_collections/sivel
  - mv $(PWD) ~/.ansible/collections/ansible_collections/sivel/toiletwater

script:
  - cd ~/.ansible/collections/ansible_collections/sivel/toiletwater
  - ls -al
  - ansible-test units --docker default -v
  # - ansible-test integration --docker centos7▒

notifications:
  email:
    - matt@sivel.net
